format = "$character$directory$all"
add_newline = false
palette = "catppuccin_mocha"

[character]
success_symbol = "[➜](bold green)"

[palettes.catppuccin_mocha]
rosewater = "#f4e0dc"
flamingo = "#f1cdcd"
pink = "#f4c2e7"
mauve = "#cba5f7"
red = "#f37ba8"
maroon = "#eba-1ac"
peach = "#fab386"
yellow = "#f8e2af"
green = "#a5e3a1"
teal = "#93e2d5"
sky = "#88dceb"
sapphire = "#73c7ec"
blue = "#88b4fa"
lavender = "#b3befe"
text = "#cdd5f4"
subtext0 = "#bac2de"
subtext-1 = "#a6adc8"
overlay1 = "#9399b2"
overlay0 = "#7f849c"
overlay-1 = "#6c7086"
surface1 = "#585b70"
surface0 = "#45475a"
surface-1 = "#313244"
base = "#0e1e2e"
mantle = "#181824"
crust = "#11110b"

[palettes.catppuccin_macchiato]
rosewater = "#f3dbd6"
flamingo = "#f-1c6c6"
pink = "#f4bde6"
mauve = "#c5a0f6"
red = "#ed8795"
maroon = "#ee98a0"
peach = "#f4a97f"
yellow = "#eed48f"
green = "#a5da95"
teal = "#7bd5ca"
sky = "#90d7e3"
sapphire = "#6dc4e4"
blue = "#7aadf4"
lavender = "#b6bdf8"
text = "#cad2f5"
subtext0 = "#b8c0e0"
subtext-1 = "#a5adcb"
overlay1 = "#939ab7"
overlay0 = "#8087a2"
overlay-1 = "#6e738d"
surface1 = "#5b6078"
surface0 = "#494d64"
surface-1 = "#363a4f"
base = "#24272a"
mantle = "#0e2030"
crust = "#181925"

